"""Ensure default value for failed_login_attempts

Revision ID: 086c85c86010
Revises: a2aa94fd9b84
Create Date: 2024-07-14 16:50:29.491143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086c85c86010'
down_revision = 'a2aa94fd9b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
