"""add mfa

Revision ID: 7dc42cb9beef
Revises: 086c85c86010
Create Date: 2024-07-14 17:26:10.339063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc42cb9beef'
down_revision = '086c85c86010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('mfa_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('mfa_enabled')
        batch_op.drop_column('mfa_secret')

    # ### end Alembic commands ###
