"""Add email_change_pending to User model

Revision ID: a0234cbde983
Revises: 7dc42cb9beef
Create Date: 2024-07-14 23:22:12.711376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0234cbde983'
down_revision = '7dc42cb9beef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_change_pending', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_change_pending')

    # ### end Alembic commands ###
